// flow-typed signature: 7421ae9cf2faded5fcefe3d1dfe0a8ca
// flow-typed version: <<STUB>>/snake-case_v^2.1.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'snake-case'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'snake-case' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'snake-case/snake-case' {
  declare module.exports: any;
}

// Filename aliases
declare module 'snake-case/snake-case.js' {
  declare module.exports: $Exports<'snake-case/snake-case'>;
}
